component_depth: 1
languages:
- java
exclude:
- ./bin/.*
- ./bin/antidote/.*
- ./bin/docs/.*
- ./bin/docs/ant2/.*
- ./bin/docs/antlibs/.*
- ./bin/docs/antlibs/antunit/.*
- ./bin/docs/antlibs/compress/.*
- ./bin/docs/antlibs/dotnet/.*
- ./bin/docs/antlibs/props/.*
- ./bin/docs/antlibs/svn/.*
- ./bin/docs/images/.*
- ./bin/docs/manual/.*
- ./bin/docs/manual/Integration/.*
- ./bin/docs/manual/Tasks/.*
- ./bin/docs/manual/Types/.*
- ./bin/docs/manual/stylesheets/.*
- ./bin/docs/projects/.*
- ./bin/docs/slides/.*
- ./bin/docs/webtest/.*
- ./bin/docs/webtest/gettest/.*
- ./bin/etc/.*
- ./bin/etc/checkstyle/.*
- ./bin/etc/performance/.*
- ./bin/etc/poms/.*
- ./bin/etc/poms/ant/.*
- ./bin/etc/poms/ant-antlr/.*
- ./bin/etc/poms/ant-apache-bcel/.*
- ./bin/etc/poms/ant-apache-bsf/.*
- ./bin/etc/poms/ant-apache-log4j/.*
- ./bin/etc/poms/ant-apache-oro/.*
- ./bin/etc/poms/ant-apache-regexp/.*
- ./bin/etc/poms/ant-apache-resolver/.*
- ./bin/etc/poms/ant-apache-xalan2/.*
- ./bin/etc/poms/ant-commons-logging/.*
- ./bin/etc/poms/ant-commons-net/.*
- ./bin/etc/poms/ant-jai/.*
- ./bin/etc/poms/ant-javamail/.*
- ./bin/etc/poms/ant-jdepend/.*
- ./bin/etc/poms/ant-jmf/.*
- ./bin/etc/poms/ant-jsch/.*
- ./bin/etc/poms/ant-junit/.*
- ./bin/etc/poms/ant-junit4/.*
- ./bin/etc/poms/ant-launcher/.*
- ./bin/etc/poms/ant-netrexx/.*
- ./bin/etc/poms/ant-swing/.*
- ./bin/etc/poms/ant-testutil/.*
- ./bin/etc/testcases/.*
- ./bin/etc/testcases/core/.*
- ./bin/etc/testcases/core/dispatch/.*
- ./bin/etc/testcases/core/include/.*
- ./bin/etc/testcases/core/include/basic/.*
- ./bin/etc/testcases/core/include/frag#ment/.*
- ./bin/etc/testcases/core/include/included_file_parse_error/.*
- ./bin/etc/testcases/core/include/included_file_task_error/.*
- ./bin/etc/testcases/core/include/including_file_parse_error/.*
- ./bin/etc/testcases/core/include/including_file_task_error/.*
- ./bin/etc/testcases/core/include/with space/.*
- ./bin/etc/testcases/core/loaderref/.*
- ./bin/etc/testcases/core/topleveltasks/.*
- ./bin/etc/testcases/filters/.*
- ./bin/etc/testcases/filters/expected/.*
- ./bin/etc/testcases/filters/input/.*
- ./bin/etc/testcases/taskdefs/.*
- ./bin/etc/testcases/taskdefs/ant/.*
- ./bin/etc/testcases/taskdefs/checksum/.*
- ./bin/etc/testcases/taskdefs/checksum/foo/.*
- ./bin/etc/testcases/taskdefs/checksum/foo/zap/.*
- ./bin/etc/testcases/taskdefs/concat-input/.*
- ./bin/etc/testcases/taskdefs/conditions/.*
- ./bin/etc/testcases/taskdefs/conditions/jars/.*
- ./bin/etc/testcases/taskdefs/copy/.*
- ./bin/etc/testcases/taskdefs/copy/expected/.*
- ./bin/etc/testcases/taskdefs/copy/input/.*
- ./bin/etc/testcases/taskdefs/email/.*
- ./bin/etc/testcases/taskdefs/exec/.*
- ./bin/etc/testcases/taskdefs/expected/.*
- ./bin/etc/testcases/taskdefs/fixcrlf/.*
- ./bin/etc/testcases/taskdefs/import/.*
- ./bin/etc/testcases/taskdefs/import/subdir/.*
- ./bin/etc/testcases/taskdefs/import/symlinks/.*
- ./bin/etc/testcases/taskdefs/import/symlinks/d1/.*
- ./bin/etc/testcases/taskdefs/import/symlinks/d2/.*
- ./bin/etc/testcases/taskdefs/import/symlinks/d3a/.*
- ./bin/etc/testcases/taskdefs/javadoc/.*
- ./bin/etc/testcases/taskdefs/javadoc/java/.*
- ./bin/etc/testcases/taskdefs/manifests/.*
- ./bin/etc/testcases/taskdefs/optional/.*
- ./bin/etc/testcases/taskdefs/optional/antlr/.*
- ./bin/etc/testcases/taskdefs/optional/depend/.*
- ./bin/etc/testcases/taskdefs/optional/i18n/.*
- ./bin/etc/testcases/taskdefs/optional/i18n/translate/.*
- ./bin/etc/testcases/taskdefs/optional/i18n/translate/expected/.*
- ./bin/etc/testcases/taskdefs/optional/i18n/translate/expected/de/.*
- ./bin/etc/testcases/taskdefs/optional/i18n/translate/input/.*
- ./bin/etc/testcases/taskdefs/optional/image/.*
- ./bin/etc/testcases/taskdefs/optional/javah/.*
- ./bin/etc/testcases/taskdefs/optional/jdepend/.*
- ./bin/etc/testcases/taskdefs/optional/jsp/.*
- ./bin/etc/testcases/taskdefs/optional/jsp/WEB-INF/.*
- ./bin/etc/testcases/taskdefs/optional/junit/.*
- ./bin/etc/testcases/taskdefs/optional/junitreport/.*
- ./bin/etc/testcases/taskdefs/optional/junitreport-with-include/.*
- ./bin/etc/testcases/taskdefs/optional/native2ascii/.*
- ./bin/etc/testcases/taskdefs/optional/native2ascii/expected/.*
- ./bin/etc/testcases/taskdefs/optional/native2ascii/input/.*
- ./bin/etc/testcases/taskdefs/optional/net/.*
- ./bin/etc/testcases/taskdefs/optional/perforce/.*
- ./bin/etc/testcases/taskdefs/optional/script/.*
- ./bin/etc/testcases/taskdefs/optional/sos/.*
- ./bin/etc/testcases/taskdefs/optional/unix/.*
- ./bin/etc/testcases/taskdefs/optional/vss/.*
- ./bin/etc/testcases/taskdefs/optional/xml/.*
- ./bin/etc/testcases/taskdefs/recorder/.*
- ./bin/etc/testcases/taskdefs/replace/.*
- ./bin/etc/testcases/taskdefs/rmic/.*
- ./bin/etc/testcases/taskdefs/style/.*
- ./bin/etc/testcases/taskdefs/subant/.*
- ./bin/etc/testcases/taskdefs/subant/subant-test1/.*
- ./bin/etc/testcases/taskdefs/subant/subant-test2/.*
- ./bin/etc/testcases/taskdefs/xmlproperty/.*
- ./bin/etc/testcases/taskdefs/xmlproperty/goldfiles/.*
- ./bin/etc/testcases/taskdefs/xmlproperty/inputs/.*
- ./bin/etc/testcases/taskdefs/zip/.*
- ./bin/etc/testcases/types/.*
- ./bin/etc/testcases/types/gold/.*
- ./bin/etc/testcases/types/mappers/.*
- ./bin/etc/testcases/types/selectors/.*
- ./bin/etc/testcases/util/.*
- ./bin/lib/.*
- ./bin/org/.*
- ./bin/org/apache/.*
- ./bin/org/apache/tools/.*
- ./bin/org/apache/tools/ant/.*
- ./bin/org/apache/tools/ant/dispatch/.*
- ./bin/org/apache/tools/ant/filters/.*
- ./bin/org/apache/tools/ant/filters/util/.*
- ./bin/org/apache/tools/ant/helper/.*
- ./bin/org/apache/tools/ant/input/.*
- ./bin/org/apache/tools/ant/launch/.*
- ./bin/org/apache/tools/ant/listener/.*
- ./bin/org/apache/tools/ant/loader/.*
- ./bin/org/apache/tools/ant/property/.*
- ./bin/org/apache/tools/ant/taskdefs/.*
- ./bin/org/apache/tools/ant/taskdefs/compilers/.*
- ./bin/org/apache/tools/ant/taskdefs/condition/.*
- ./bin/org/apache/tools/ant/taskdefs/cvslib/.*
- ./bin/org/apache/tools/ant/taskdefs/dir1/.*
- ./bin/org/apache/tools/ant/taskdefs/dir2/.*
- ./bin/org/apache/tools/ant/taskdefs/email/.*
- ./bin/org/apache/tools/ant/taskdefs/optional/.*
- ./bin/org/apache/tools/ant/taskdefs/optional/ccm/.*
- ./bin/org/apache/tools/ant/taskdefs/optional/clearcase/.*
- ./bin/org/apache/tools/ant/taskdefs/optional/depend/.*
- ./bin/org/apache/tools/ant/taskdefs/optional/depend/constantpool/.*
- ./bin/org/apache/tools/ant/taskdefs/optional/ejb/.*
- ./bin/org/apache/tools/ant/taskdefs/optional/extension/.*
- ./bin/org/apache/tools/ant/taskdefs/optional/extension/resolvers/.*
- ./bin/org/apache/tools/ant/taskdefs/optional/i18n/.*
- ./bin/org/apache/tools/ant/taskdefs/optional/image/.*
- ./bin/org/apache/tools/ant/taskdefs/optional/j2ee/.*
- ./bin/org/apache/tools/ant/taskdefs/optional/javacc/.*
- ./bin/org/apache/tools/ant/taskdefs/optional/javah/.*
- ./bin/org/apache/tools/ant/taskdefs/optional/jdepend/.*
- ./bin/org/apache/tools/ant/taskdefs/optional/jlink/.*
- ./bin/org/apache/tools/ant/taskdefs/optional/jsp/.*
- ./bin/org/apache/tools/ant/taskdefs/optional/jsp/compilers/.*
- ./bin/org/apache/tools/ant/taskdefs/optional/junit/.*
- ./bin/org/apache/tools/ant/taskdefs/optional/native2ascii/.*
- ./bin/org/apache/tools/ant/taskdefs/optional/net/.*
- ./bin/org/apache/tools/ant/taskdefs/optional/perforce/.*
- ./bin/org/apache/tools/ant/taskdefs/optional/pvcs/.*
- ./bin/org/apache/tools/ant/taskdefs/optional/script/.*
- ./bin/org/apache/tools/ant/taskdefs/optional/sos/.*
- ./bin/org/apache/tools/ant/taskdefs/optional/sound/.*
- ./bin/org/apache/tools/ant/taskdefs/optional/splash/.*
- ./bin/org/apache/tools/ant/taskdefs/optional/ssh/.*
- ./bin/org/apache/tools/ant/taskdefs/optional/testing/.*
- ./bin/org/apache/tools/ant/taskdefs/optional/unix/.*
- ./bin/org/apache/tools/ant/taskdefs/optional/vss/.*
- ./bin/org/apache/tools/ant/taskdefs/optional/windows/.*
- ./bin/org/apache/tools/ant/taskdefs/rmic/.*
- ./bin/org/apache/tools/ant/types/.*
- ./bin/org/apache/tools/ant/types/conditions/.*
- ./bin/org/apache/tools/ant/types/mappers/.*
- ./bin/org/apache/tools/ant/types/optional/.*
- ./bin/org/apache/tools/ant/types/optional/depend/.*
- ./bin/org/apache/tools/ant/types/optional/image/.*
- ./bin/org/apache/tools/ant/types/resolver/.*
- ./bin/org/apache/tools/ant/types/selectors/.*
- ./bin/org/apache/tools/ant/types/selectors/modifiedselector/.*
- ./bin/org/apache/tools/ant/types/spi/.*
- ./bin/org/apache/tools/ant/util/.*
- ./bin/org/apache/tools/ant/util/depend/.*
- ./bin/org/apache/tools/ant/util/depend/bcel/.*
- ./bin/org/apache/tools/ant/util/facade/.*
- ./bin/org/apache/tools/ant/util/java15/.*
- ./bin/org/apache/tools/ant/util/optional/.*
- ./bin/org/apache/tools/ant/util/regexp/.*
- ./bin/org/apache/tools/bzip2/.*
- ./bin/org/apache/tools/mail/.*
- ./bin/org/apache/tools/tar/.*
- ./bin/org/apache/tools/zip/.*
- ./bin/org/example/.*
- ./bin/org/example/junit/.*
- ./bin/org/example/tasks/.*
- ./bin/org/example/types/.*
- ./bin/script/.*
- ./bin/task/.*
- ./bin/test/.*
- ./bin/tests/.*
- ./bin/tests/antunit/.*
- ./bin/tests/antunit/bugfixes/.*
- ./bin/tests/antunit/core/.*
- ./bin/tests/antunit/core/location/.*
- ./bin/tests/antunit/core/projecthelpers/.*
- ./bin/tests/antunit/core/uuencode/.*
- ./bin/tests/antunit/filters/.*
- ./bin/tests/antunit/filters/expected/.*
- ./bin/tests/antunit/filters/input/.*
- ./bin/tests/antunit/taskdefs/.*
- ./bin/tests/antunit/taskdefs/condition/.*
- ./bin/tests/antunit/taskdefs/cvs/.*
- ./bin/tests/antunit/taskdefs/cvs/repository/.*
- ./bin/tests/antunit/taskdefs/cvs/repository/CVSROOT/.*
- ./bin/tests/antunit/taskdefs/cvs/repository/ant module 2/.*
- ./bin/tests/antunit/taskdefs/cvs/repository/antmodule1/.*
- ./bin/tests/antunit/taskdefs/cvs/repository/antmodule3/.*
- ./bin/tests/antunit/taskdefs/exec/.*
- ./bin/tests/antunit/taskdefs/exec/expected/.*
- ./bin/tests/antunit/taskdefs/exec/input/.*
- ./bin/tests/antunit/taskdefs/importtests/.*
- ./bin/tests/antunit/taskdefs/optional/.*
- ./bin/tests/antunit/taskdefs/optional/depend/.*
- ./bin/tests/antunit/taskdefs/optional/junit/.*
- ./bin/tests/antunit/taskdefs/optional/script/.*
- ./bin/tests/antunit/taskdefs/optional/unix/.*
- ./bin/tests/antunit/taskdefs/optional/windows/.*
- ./bin/tests/antunit/taskdefs/subant-helper/.*
- ./bin/tests/antunit/taskdefs/truncate/.*
- ./bin/tests/antunit/taskdefs/xslt/.*
- ./bin/tests/antunit/taskdefs/zip/.*
- ./bin/tests/antunit/types/.*
- ./bin/tests/antunit/types/conditions/.*
- ./bin/tests/antunit/types/selectors/.*
- ./docs/.*
- ./docs/ant2/.*
- ./docs/antlibs/.*
- ./docs/antlibs/antunit/.*
- ./docs/antlibs/compress/.*
- ./docs/antlibs/dotnet/.*
- ./docs/antlibs/props/.*
- ./docs/antlibs/svn/.*
- ./docs/images/.*
- ./docs/manual/.*
- ./docs/manual/Integration/.*
- ./docs/manual/Tasks/.*
- ./docs/manual/Types/.*
- ./docs/manual/stylesheets/.*
- ./docs/projects/.*
- ./docs/slides/.*
- ./docs/webtest/.*
- ./docs/webtest/gettest/.*
- ./lib/.*
